### ISSUE TITLE
Изучить Open API спецификацию (swagger)

### ISSUE THREAD

**Issue by zimin-krsk** [nataTerr/online-store-portal#5]
### Проблематика
Для взаимодействия с фронтом необходимо спроектировать REST методы

### Материалы для изучения
- [x] Общая информация про сваггер с примерами:
https://habr.com/ru/post/541592/
- [x] Более практичное применение:
https://habr.com/ru/post/536388/

### Что необходимо сделать

1. Ознакомиться с подходами проектирования взаимодействия между приложениями
2. Понять чем один подход отличается от другого и в каком случае необходимо использовать тот или иной подход
3. Научиться понимать какой http метод, какие параметры передавать, какой должен быть ответ и почему. Почему один способ предпочтительнее и в какой момент.

### Комментарий
Т.к. эта задача по большей части творческая, то можно взаимодействовать со мной, уточняя требования.\
Но только после того как будут усвоены основные правила, описанные в статьях.

В результате работы над задачей должно быть понимание, каким образом можно спроектировать методы для сервиса site-api

### Официальная документация Open API
https://swagger.io/docs/specification/about/

**Comment by nataTerr** [comment]
-  Более практичное применение:
https://habr.com/ru/post/536388/

     Доступ к публикации закрыт. Предложи еще что нибудь, т.к. материала по ссылке https://habr.com/ru/post/541592/ для меня мало. Нужны еще разъяснения.

**Comment by zimin-krsk** [comment]
вот вроде прикольный учебник с детальным погружением в спецификацию:
https://starkovden.github.io/introduction-openapi-and-swagger.html
